- name: Deploy app in new ns
- hosts: localhost
  tasks:
    - name: Create a Kubernetes namespace
      community.kubernetes.k8s:
        api_version: v1
        kind: Namespace
        metadata:
          name: my-app
        kubeconfig: /path/to/my-kubeconfig




























